// <auto-generated />
namespace _00Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Trycreatedbatsqlexpresssever : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Trycreatedbatsqlexpresssever));
        
        string IMigrationMetadata.Id
        {
            get { return "201910281942438_Try create db at sqlexpress sever"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
